
import React, { useState } from 'react';
import { X, ShieldAlert } from 'lucide-react';

const Disclaimer: React.FC = () => {
  const [visible, setVisible] = useState(true);

  if (!visible) return null;

  return (
    <div className="fixed bottom-0 left-0 right-0 bg-slate-900 text-slate-300 p-4 z-50 border-t border-slate-700 shadow-2xl print:hidden animate-in slide-in-from-bottom-5">
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="flex items-start gap-3">
          <ShieldAlert className="text-orange-500 flex-shrink-0 mt-1" size={20} />
          <div className="text-xs font-medium leading-relaxed">
            <strong className="text-white uppercase tracking-wider block mb-1">Unofficial Community Platform</strong>
            <p>
              "India PE Connect Platform" is an independent educational tool and is <span className="text-orange-400 font-bold">NOT affiliated</span> with the Ministry of Youth Affairs and Sports, Khelo India, CBSE, or NCERT. 
              All logos and trademarks belong to their respective owners. 
              Content is generated by AI and should be verified by a certified professional before implementation in schools.
            </p>
          </div>
        </div>
        <button 
          onClick={() => setVisible(false)}
          className="bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg text-xs font-bold transition-colors flex items-center whitespace-nowrap"
        >
          <X size={14} className="mr-1" /> Dismiss
        </button>
      </div>
    </div>
  );
};

export default Disclaimer;
