import React, { useState } from 'react';
import { Zap, Loader2, Share2, RotateCcw, Clock, AlertCircle, ChevronRight, Dumbbell, Activity, Music, MessageCircle } from 'lucide-react';
import { callAIBase } from '../services/geminiService.ts';

// ─── Warm-Up Generator ────────────────────────────────────────────────────────
const WarmupGenerator: React.FC = () => {
  const [sport, setSport] = useState('Football');
  const [duration, setDuration] = useState('10 min');
  const [ageGroup, setAgeGroup] = useState('12-15 years');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    setLoading(true); setError(null);
    try {
      const res = await callAIBase({
        model: 'claude-sonnet',
        contents: `Generate a structured warm-up routine. Sport: ${sport}. Duration: ${duration}. Age group: ${ageGroup}.`,
        config: {
          systemInstruction: `PE Expert. Return JSON: { title, totalDuration, phases: [{ name, duration, exercises: [{ name, reps, description }] }], coachingTips: string[] }. Sport-specific preparation. Age-appropriate.`,
          responseMimeType: 'application/json',
        },
      });
      const d = JSON.parse(res.text.replace(/```json|```/g, '').trim());
      setResult(d);
    } catch (e: any) { setError(e.message || 'Failed to generate.'); }
    finally { setLoading(false); }
  };

  const share = () => {
    if (!result) return;
    const exercises = result.phases?.map((p: any) => `${p.name} (${p.duration}):\n${p.exercises?.map((e: any) => `• ${e.name}: ${e.reps}`).join('\n')}`).join('\n\n') || '';
    window.open(`https://wa.me/?text=${encodeURIComponent(`🏃 Warm-Up: ${result.title}\n\n${exercises}\n\nGenerated by SmartPE India`)}`, '_blank');
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="bg-gradient-to-r from-rose-500 to-orange-500 rounded-[2.5rem] p-10 text-white shadow-xl relative overflow-hidden">
        <div className="relative z-10 max-w-2xl">
          <h2 className="text-4xl font-black mb-4 uppercase tracking-tighter">5-Min Warm-Up Generator</h2>
          <p className="text-rose-100 text-lg font-medium leading-relaxed">AI-crafted warm-up routines specific to your sport and age group.</p>
        </div>
        <Zap className="absolute right-[-20px] bottom-[-40px] w-64 h-64 text-white/10 rotate-12" />
      </div>

      <div className="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          {[
            { label: 'Sport / Activity', val: sport, set: setSport, type: 'input', placeholder: 'e.g. Cricket, Football, Athletics' },
            { label: 'Duration', val: duration, set: setDuration, type: 'select', options: ['5 min', '8 min', '10 min', '15 min', '20 min'] },
            { label: 'Age Group', val: ageGroup, set: setAgeGroup, type: 'select', options: ['6-10 years', '10-12 years', '12-15 years', '15-18 years', 'Adults'] },
          ].map(field => (
            <div key={field.label}>
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block">{field.label}</label>
              {field.type === 'input' ? (
                <input value={field.val} onChange={e => field.set(e.target.value)} placeholder={field.placeholder} className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl font-bold outline-none focus:ring-2 focus:ring-rose-300" />
              ) : (
                <select value={field.val} onChange={e => field.set(e.target.value)} className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl font-bold outline-none focus:ring-2 focus:ring-rose-300">
                  {field.options?.map(o => <option key={o}>{o}</option>)}
                </select>
              )}
            </div>
          ))}
        </div>
        {error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm flex gap-2"><AlertCircle size={16} />{error}</div>}
        <button onClick={generate} disabled={loading} className="w-full py-4 bg-rose-500 text-white rounded-2xl font-black text-sm uppercase tracking-widest hover:bg-rose-600 disabled:opacity-50 transition-all flex items-center justify-center gap-2">
          {loading ? <><Loader2 className="animate-spin" size={18} /> Generating...</> : <><Zap size={18} /> Generate Warm-Up</>}
        </button>
      </div>

      {result && (
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
          <div className="bg-gradient-to-r from-rose-500 to-orange-500 p-5 text-white flex justify-between items-start">
            <div>
              <p className="text-rose-100 text-xs font-bold uppercase tracking-widest mb-1">🏃 Warm-Up Ready</p>
              <h3 className="text-xl font-black">{result.title}</h3>
              <p className="text-rose-100 text-sm mt-1">Total: {result.totalDuration}</p>
            </div>
            <div className="flex gap-2">
              <button onClick={share} className="flex items-center gap-2 px-4 py-2 bg-white/20 rounded-xl text-sm font-bold hover:bg-white/30 transition-colors"><Share2 size={14} />WhatsApp</button>
              <button onClick={() => setResult(null)} className="flex items-center gap-2 px-4 py-2 bg-white/10 rounded-xl text-sm font-bold hover:bg-white/20 transition-colors"><RotateCcw size={14} />New</button>
            </div>
          </div>
          <div className="p-6 space-y-4">
            {result.phases?.map((phase: any, i: number) => (
              <div key={i} className="border border-slate-100 rounded-2xl overflow-hidden">
                <div className="bg-rose-50 px-5 py-3 flex items-center justify-between">
                  <h4 className="font-black text-rose-900 text-sm uppercase tracking-wide">{phase.name}</h4>
                  <span className="text-xs font-bold text-rose-600 flex items-center gap-1"><Clock size={12} />{phase.duration}</span>
                </div>
                <div className="p-4 space-y-2">
                  {phase.exercises?.map((ex: any, j: number) => (
                    <div key={j} className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                      <ChevronRight size={14} className="text-rose-400 mt-0.5 flex-shrink-0" />
                      <div>
                        <span className="font-bold text-slate-800 text-sm">{ex.name}</span>
                        {ex.reps && <span className="text-rose-600 font-black text-xs ml-2">× {ex.reps}</span>}
                        {ex.description && <p className="text-xs text-slate-500 mt-0.5">{ex.description}</p>}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
            {result.coachingTips?.length > 0 && (
              <div className="p-4 bg-amber-50 rounded-2xl border border-amber-100">
                <h4 className="font-black text-amber-700 text-xs uppercase tracking-widest mb-2">💡 Coaching Tips</h4>
                {result.coachingTips.map((tip: string, i: number) => (<p key={i} className="text-xs text-amber-800 flex items-start gap-1"><ChevronRight size={12} className="mt-0.5 flex-shrink-0" />{tip}</p>))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

// ─── Sports Quiz Generator ────────────────────────────────────────────────────
const SportsQuiz: React.FC = () => {
  const [sport, setSport] = useState('Cricket');
  const [difficulty, setDifficulty] = useState('Medium');
  const [count, setCount] = useState('10');
  const [loading, setLoading] = useState(false);
  const [quiz, setQuiz] = useState<any[] | null>(null);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    setLoading(true); setError(null); setAnswers({}); setSubmitted(false);
    try {
      const res = await callAIBase({
        model: 'claude-sonnet',
        contents: `Create a sports quiz. Sport/Topic: ${sport}. Difficulty: ${difficulty}. Number of questions: ${count}.`,
        config: {
          systemInstruction: `PE/Sports teacher. Return JSON: { title, questions: [{ question, options: string[4], answer, explanation }] }. MCQ format. 4 options each. Suitable for school students. Indian context where relevant.`,
          responseMimeType: 'application/json',
        },
      });
      const d = JSON.parse(res.text.replace(/```json|```/g, '').trim());
      setQuiz(d.questions || []);
    } catch (e: any) { setError(e.message); }
    finally { setLoading(false); }
  };

  const score = submitted ? quiz?.filter((q, i) => answers[i] === q.answer).length || 0 : 0;

  return (
    <div className="space-y-6 pb-20">
      <div className="bg-gradient-to-r from-violet-600 to-indigo-700 rounded-[2.5rem] p-10 text-white shadow-xl relative overflow-hidden">
        <div className="relative z-10 max-w-2xl">
          <h2 className="text-4xl font-black mb-4 uppercase tracking-tighter">Sports Quiz Generator</h2>
          <p className="text-violet-200 text-lg font-medium">Generate instant sports knowledge quizzes for theory classes.</p>
        </div>
        <Activity className="absolute right-[-20px] bottom-[-40px] w-64 h-64 text-white/10 rotate-12" />
      </div>

      {!quiz ? (
        <div className="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            {[
              { label: 'Sport / Topic', val: sport, set: setSport, type: 'input', placeholder: 'e.g. Cricket, Olympics, Yoga, Kabaddi' },
              { label: 'Difficulty', val: difficulty, set: setDifficulty, type: 'select', options: ['Easy', 'Medium', 'Hard'] },
              { label: 'No. of Questions', val: count, set: setCount, type: 'select', options: ['5', '8', '10', '15', '20'] },
            ].map(field => (
              <div key={field.label}>
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block">{field.label}</label>
                {field.type === 'input' ? (
                  <input value={field.val} onChange={e => field.set(e.target.value)} placeholder={field.placeholder} className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl font-bold outline-none focus:ring-2 focus:ring-violet-300" />
                ) : (
                  <select value={field.val} onChange={e => field.set(e.target.value)} className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl font-bold outline-none focus:ring-2 focus:ring-violet-300">
                    {field.options?.map(o => <option key={o}>{o}</option>)}
                  </select>
                )}
              </div>
            ))}
          </div>
          {error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm">{error}</div>}
          <button onClick={generate} disabled={loading} className="w-full py-4 bg-violet-600 text-white rounded-2xl font-black text-sm uppercase tracking-widest hover:bg-violet-700 disabled:opacity-50 transition-all flex items-center justify-center gap-2">
            {loading ? <><Loader2 className="animate-spin" size={18} />Generating Quiz...</> : <><Activity size={18} />Generate Quiz</>}
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          {submitted && (
            <div className={`rounded-2xl p-6 text-center ${score >= quiz.length * 0.7 ? 'bg-emerald-50 border-2 border-emerald-200' : 'bg-amber-50 border-2 border-amber-200'}`}>
              <div className="text-5xl font-black mb-2 text-slate-800">{score} / {quiz.length}</div>
              <p className={`font-black text-lg ${score >= quiz.length * 0.7 ? 'text-emerald-700' : 'text-amber-700'}`}>{score >= quiz.length * 0.7 ? '🏆 Excellent!' : score >= quiz.length * 0.5 ? '👍 Good effort!' : '📚 Keep practicing!'}</p>
            </div>
          )}
          {quiz.map((q, i) => (
            <div key={i} className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
              <div className="flex items-start gap-3 mb-4">
                <span className="w-7 h-7 bg-violet-600 text-white rounded-lg flex items-center justify-center text-xs font-black flex-shrink-0">{i + 1}</span>
                <p className="font-bold text-slate-800">{q.question}</p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {q.options?.map((opt: string, oi: number) => {
                  const isSelected = answers[i] === opt;
                  const isCorrect = opt === q.answer;
                  let cls = 'border border-slate-200 bg-slate-50 text-slate-700';
                  if (submitted) {
                    if (isCorrect) cls = 'border-2 border-emerald-300 bg-emerald-50 text-emerald-800';
                    else if (isSelected) cls = 'border-2 border-red-300 bg-red-50 text-red-800';
                  } else if (isSelected) cls = 'border-2 border-violet-300 bg-violet-50 text-violet-800';
                  return (
                    <button key={oi} onClick={() => !submitted && setAnswers(p => ({ ...p, [i]: opt }))} disabled={submitted} className={`p-3 rounded-xl text-left text-sm font-medium transition-all ${cls} hover:opacity-80`}>
                      <span className="font-black mr-2 text-xs">{String.fromCharCode(65 + oi)}.</span>{opt}
                    </button>
                  );
                })}
              </div>
              {submitted && q.explanation && (
                <div className="mt-3 p-3 bg-violet-50 border border-violet-100 rounded-xl">
                  <p className="text-xs text-violet-800 font-medium"><span className="font-black">💡 Explanation: </span>{q.explanation}</p>
                </div>
              )}
            </div>
          ))}
          <div className="flex gap-3 flex-wrap">
            {!submitted ? (
              <button onClick={() => setSubmitted(true)} className="flex-1 py-3 bg-violet-600 text-white rounded-2xl font-black text-sm uppercase tracking-widest hover:bg-violet-700 transition-all">Submit Answers</button>
            ) : null}
            <button onClick={() => { setQuiz(null); setAnswers({}); setSubmitted(false); }} className="px-6 py-3 bg-slate-100 text-slate-600 rounded-2xl font-black text-sm uppercase tracking-widest hover:bg-slate-200 transition-all flex items-center gap-2"><RotateCcw size={16} />New Quiz</button>
          </div>
        </div>
      )}
    </div>
  );
};

// ─── Injury First Aid Guide ───────────────────────────────────────────────────
const COMMON_INJURIES = ['Ankle Sprain', 'Muscle Cramp', 'Nose Bleed', 'Knee Pain', 'Wrist Sprain', 'Head Impact', 'Dehydration', 'Blister', 'Shin Splints', 'Other'];

const InjuryFirstAid: React.FC = () => {
  const [injury, setInjury] = useState('');
  const [custom, setCustom] = useState('');
  const [loading, setLoading] = useState(false);
  const [guide, setGuide] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    const target = injury === 'Other' ? custom : injury;
    if (!target.trim()) return;
    setLoading(true); setError(null);
    try {
      const res = await callAIBase({
        model: 'claude-sonnet',
        contents: `First aid guide for PE/sports injury: ${target}`,
        config: {
          systemInstruction: `Sports First Aid Expert. Return JSON: { injury, severity, immediateSteps: string[], doNot: string[], whenToSeekDoctor: string, prevention: string[], returnToPlay: string }. Clear, concise, school-appropriate steps.`,
          responseMimeType: 'application/json',
        },
      });
      const d = JSON.parse(res.text.replace(/```json|```/g, '').trim());
      setGuide(d);
    } catch (e: any) { setError(e.message); }
    finally { setLoading(false); }
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="bg-gradient-to-r from-red-600 to-rose-600 rounded-[2.5rem] p-10 text-white shadow-xl relative overflow-hidden">
        <div className="relative z-10 max-w-2xl">
          <h2 className="text-4xl font-black mb-4 uppercase tracking-tighter">Injury First Aid Guide</h2>
          <p className="text-red-100 text-lg font-medium">Instant PE first aid protocols for common sports injuries.</p>
        </div>
        <Activity className="absolute right-[-20px] bottom-[-40px] w-64 h-64 text-white/10 rotate-12" />
      </div>

      <div className="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm">
        <h3 className="text-lg font-black text-slate-800 mb-4">Select Injury Type</h3>
        <div className="flex flex-wrap gap-2 mb-6">
          {COMMON_INJURIES.map(inj => (
            <button key={inj} onClick={() => setInjury(inj)} className={`px-4 py-2 rounded-xl text-sm font-bold transition-all ${injury === inj ? 'bg-red-600 text-white' : 'bg-slate-50 text-slate-600 hover:bg-red-50 hover:text-red-700'}`}>{inj}</button>
          ))}
        </div>
        {injury === 'Other' && (
          <input value={custom} onChange={e => setCustom(e.target.value)} placeholder="Describe the injury..." className="w-full border border-slate-200 rounded-xl px-4 py-3 text-sm mb-4 outline-none focus:ring-2 focus:ring-red-300" />
        )}
        {error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm">{error}</div>}
        <button onClick={generate} disabled={!injury || loading} className="w-full py-4 bg-red-600 text-white rounded-2xl font-black text-sm uppercase tracking-widest hover:bg-red-700 disabled:opacity-50 transition-all flex items-center justify-center gap-2">
          {loading ? <><Loader2 className="animate-spin" size={18} />Loading Guide...</> : <>🩺 Get First Aid Guide</>}
        </button>
        <p className="text-xs text-slate-400 text-center mt-3">⚠️ For serious injuries always call emergency services. This is a guidance tool only.</p>
      </div>

      {guide && (
        <div className="space-y-4">
          <div className={`rounded-2xl p-4 flex items-center gap-3 ${guide.severity === 'High' ? 'bg-red-50 border-2 border-red-300' : guide.severity === 'Medium' ? 'bg-amber-50 border-2 border-amber-300' : 'bg-emerald-50 border-2 border-emerald-300'}`}>
            <span className="text-2xl">{guide.severity === 'High' ? '🔴' : guide.severity === 'Medium' ? '🟡' : '🟢'}</span>
            <div>
              <p className="font-black text-slate-800">{guide.injury}</p>
              <p className="text-xs text-slate-600 font-bold">Severity: {guide.severity}</p>
            </div>
          </div>
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6 space-y-5">
            <div>
              <h4 className="font-black text-slate-800 text-sm uppercase tracking-wider mb-3 flex items-center gap-2">✅ Immediate Steps</h4>
              {guide.immediateSteps?.map((step: string, i: number) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-emerald-50 rounded-xl mb-2 border border-emerald-100">
                  <span className="w-6 h-6 bg-emerald-600 text-white rounded-full flex items-center justify-center text-xs font-black flex-shrink-0">{i + 1}</span>
                  <p className="text-sm text-emerald-900 font-medium">{step}</p>
                </div>
              ))}
            </div>
            {guide.doNot?.length > 0 && (
              <div>
                <h4 className="font-black text-slate-800 text-sm uppercase tracking-wider mb-3">❌ Do NOT</h4>
                {guide.doNot.map((item: string, i: number) => <p key={i} className="text-sm text-red-700 flex items-start gap-2 mb-1"><span className="font-black">✗</span>{item}</p>)}
              </div>
            )}
            {guide.whenToSeekDoctor && (
              <div className="p-4 bg-red-50 border border-red-100 rounded-2xl">
                <h4 className="font-black text-red-700 text-xs uppercase tracking-widest mb-1">🏥 When to See a Doctor</h4>
                <p className="text-sm text-red-800">{guide.whenToSeekDoctor}</p>
              </div>
            )}
            {guide.returnToPlay && (
              <div className="p-4 bg-blue-50 border border-blue-100 rounded-2xl">
                <h4 className="font-black text-blue-700 text-xs uppercase tracking-widest mb-1">🏃 Return to Play</h4>
                <p className="text-sm text-blue-800">{guide.returnToPlay}</p>
              </div>
            )}
          </div>
          <button onClick={() => setGuide(null)} className="flex items-center gap-2 px-6 py-3 bg-slate-100 text-slate-600 rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-slate-200 transition-all"><RotateCcw size={14} />New Guide</button>
        </div>
      )}
    </div>
  );
};

// ─── WhatsApp Lesson Summary ──────────────────────────────────────────────────
const WhatsAppSummary: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [keyPoints, setKeyPoints] = useState('');
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    if (!topic.trim()) return;
    setLoading(true); setError(null);
    try {
      const res = await callAIBase({
        model: 'claude-sonnet',
        contents: `Generate a concise PE lesson summary for WhatsApp. Topic: ${topic}. Key points addressed: ${keyPoints}`,
        config: {
          systemInstruction: `PE Teacher. Generate a friendly, emoji-rich WhatsApp message that summarizes the lesson for parents/students. Include: 📝 Lesson Summary, 🎯 3 Key Takeaways, and 🏠 Home activity. Keep it brief.`,
        },
      });
      setSummary(res.text);
    } catch (e: any) { setError(e.message); }
    finally { setLoading(false); }
  };

  const share = () => {
    if (!summary) return;
    window.open(`https://wa.me/?text=${encodeURIComponent(summary)}`, '_blank');
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="bg-gradient-to-r from-emerald-600 to-teal-700 rounded-[2.5rem] p-10 text-white shadow-xl relative overflow-hidden">
        <div className="relative z-10 max-w-2xl">
          <h2 className="text-4xl font-black mb-4 uppercase tracking-tighter">WhatsApp Lesson Summary</h2>
          <p className="text-emerald-100 text-lg font-medium">Generate a professional lesson summary to share instantly with parents & students.</p>
        </div>
        <MessageCircle className="absolute right-[-20px] bottom-[-40px] w-64 h-64 text-white/10 rotate-12" />
      </div>

      <div className="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm space-y-4">
        <div>
          <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block">Lesson Topic</label>
          <input 
            value={topic} 
            onChange={e => setTopic(e.target.value)}
            placeholder="e.g. Basketball Dribbling, Athletics Start Technique..." 
            className="w-full p-4 bg-slate-50 border border-slate-200 rounded-2xl font-bold outline-none focus:ring-2 focus:ring-emerald-500" 
          />
        </div>
        <div>
          <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block">Key Points Covered (Optional)</label>
          <textarea 
            value={keyPoints} 
            onChange={e => setKeyPoints(e.target.value)}
            placeholder="e.g. Hand placement, eye contact, follow through..." 
            className="w-full p-4 bg-slate-50 border border-slate-200 rounded-2xl font-bold outline-none focus:ring-2 focus:ring-emerald-500 h-24" 
          />
        </div>
        {error && <div className="p-3 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm">{error}</div>}
        <button onClick={generate} disabled={loading || !topic} className="w-full py-4 bg-emerald-600 text-white rounded-2xl font-black text-sm uppercase tracking-widest hover:bg-emerald-700 disabled:opacity-50 transition-all flex items-center justify-center gap-2">
          {loading ? <><Loader2 className="animate-spin" size={18} />Generating Summary...</> : <><Zap size={18} /> Generate Summary</>}
        </button>
      </div>

      {summary && (
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden animate-in slide-in-from-bottom-5">
          <div className="bg-emerald-600 p-4 text-white flex justify-between items-center">
            <p className="font-black text-xs uppercase tracking-widest">Preview Summary</p>
            <button onClick={share} className="px-4 py-2 bg-white text-emerald-600 rounded-xl font-bold text-xs uppercase tracking-widest flex items-center gap-2 hover:bg-emerald-50 transition-colors">
              <Share2 size={14} /> Share on WhatsApp
            </button>
          </div>
          <div className="p-8 whitespace-pre-wrap text-slate-700 font-medium leading-relaxed">
            {summary}
          </div>
        </div>
      )}
    </div>
  );
};

// ─── Exports ─────────────────────────────────────────────────────────────────
export { WarmupGenerator, SportsQuiz, InjuryFirstAid, WhatsAppSummary };
