import React, { useState } from 'react';
import { Trophy, Loader2, Share2, RotateCcw, Calendar, Users, Megaphone, Package } from 'lucide-react';
import { generateSportsDayPlan } from '../services/geminiService.ts';
import { Language } from '../types.ts';

const SportsDayPlanner: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [schoolName, setSchoolName] = useState('');
  const [grades, setGrades] = useState('6-10');
  const [totalStudents, setTotalStudents] = useState('200');
  const [duration, setDuration] = useState('Full Day (6 hours)');
  const [theme, setTheme] = useState('Champions of Tomorrow');
  const [language, setLanguage] = useState<Language>('English');

  const handleGenerate = async () => {
    setLoading(true); setError(null);
    try {
      const result = await generateSportsDayPlan(schoolName || 'Our School', grades, totalStudents, duration, theme, language);
      setPlan(result);
    } catch (e: any) {
      setError(e.message || 'Generation failed.');
    } finally {
      setLoading(false);
    }
  };

  const handleWhatsApp = () => {
    if (!plan) return;
    const schedule = plan.schedule?.slice(0, 5).map((s: any) => `${s.time} — ${s.event}`).join('\n') || '';
    const text = `🏆 Sports Day Plan — ${plan.schoolName || schoolName}\n\nTheme: ${plan.theme}\n\n📅 Schedule:\n${schedule}\n\n🎯 Events: ${plan.events?.length || 0} events planned\n\nGenerated by SmartPE India`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100">
        <div className="flex items-center gap-3 mb-1">
          <div className="p-2 bg-yellow-100 rounded-xl"><Trophy className="text-yellow-600" size={20} /></div>
          <div>
            <h2 className="text-xl font-black text-slate-800">Sports Day Planner</h2>
            <p className="text-sm text-slate-500">AI-generated complete sports day schedule and event plan</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6 mb-6">
          <div>
            <label className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-1 block">School Name</label>
            <input value={schoolName} onChange={e => setSchoolName(e.target.value)} placeholder="e.g. St. Xavier's School" className="w-full border border-slate-200 rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-indigo-500 outline-none" />
          </div>
          <div>
            <label className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-1 block">Participating Grades</label>
            <input value={grades} onChange={e => setGrades(e.target.value)} placeholder="e.g. 6-10 or All" className="w-full border border-slate-200 rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-indigo-500 outline-none" />
          </div>
          <div>
            <label className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-1 block">Total Students</label>
            <input value={totalStudents} onChange={e => setTotalStudents(e.target.value)} placeholder="e.g. 200" className="w-full border border-slate-200 rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-indigo-500 outline-none" />
          </div>
          <div>
            <label className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-1 block">Duration</label>
            <select value={duration} onChange={e => setDuration(e.target.value)} className="w-full border border-slate-200 rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-indigo-500 outline-none bg-white">
              {['Half Day (3 hours)','Full Day (6 hours)','2 Days'].map(d => <option key={d}>{d}</option>)}
            </select>
          </div>
          <div>
            <label className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-1 block">Theme</label>
            <input value={theme} onChange={e => setTheme(e.target.value)} placeholder="e.g. Champions of Tomorrow" className="w-full border border-slate-200 rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-indigo-500 outline-none" />
          </div>
          <div>
            <label className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-1 block">Language</label>
            <select value={language} onChange={e => setLanguage(e.target.value as Language)} className="w-full border border-slate-200 rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-indigo-500 outline-none bg-white">
              {['English','Hindi','Tamil','Marathi','Bengali'].map(l => <option key={l}>{l}</option>)}
            </select>
          </div>
        </div>

        {error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm">{error}</div>}

        <button onClick={handleGenerate} disabled={loading} className="w-full py-3 bg-yellow-500 text-white rounded-xl font-black text-sm uppercase tracking-wide hover:bg-yellow-600 disabled:opacity-50 transition-all flex items-center justify-center gap-2">
          {loading ? <><Loader2 className="animate-spin" size={18} /> Planning Sports Day...</> : <><Trophy size={18} /> Generate Sports Day Plan</>}
        </button>
      </div>

      {plan && (
        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
          <div className="bg-gradient-to-r from-yellow-500 to-orange-500 p-5 text-white">
            <p className="text-yellow-100 text-xs font-bold uppercase tracking-widest mb-1">🏆 Sports Day Ready</p>
            <h3 className="text-xl font-black">{plan.title || `${plan.schoolName} Sports Day`}</h3>
            <p className="text-yellow-100 text-sm mt-1">Theme: {plan.theme}</p>
          </div>

          <div className="p-6 space-y-6">
            {plan.schedule?.length > 0 && (
              <div>
                <h4 className="font-black text-slate-700 text-sm uppercase tracking-wider mb-3 flex items-center gap-2"><Calendar size={16} className="text-yellow-600" /> Schedule</h4>
                <div className="space-y-2">
                  {plan.schedule.map((s: any, i: number) => (
                    <div key={i} className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                      <span className="text-xs font-black text-yellow-600 whitespace-nowrap bg-yellow-50 px-2 py-1 rounded-lg">{s.time}</span>
                      <div className="flex-1">
                        <p className="font-bold text-slate-800 text-sm">{s.event}</p>
                        {s.venue && <p className="text-xs text-slate-500">{s.venue} {s.participants ? `· ${s.participants}` : ''}</p>}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {plan.events?.length > 0 && (
              <div>
                <h4 className="font-black text-slate-700 text-sm uppercase tracking-wider mb-3 flex items-center gap-2"><Trophy size={16} className="text-yellow-600" /> Events ({plan.events.length})</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {plan.events.map((e: any, i: number) => (
                    <div key={i} className="p-3 bg-indigo-50 rounded-xl border border-indigo-100">
                      <p className="font-bold text-indigo-900 text-sm">{e.name}</p>
                      {e.category && <span className="text-xs text-indigo-600 font-bold">{e.category}</span>}
                      {e.rules && <p className="text-xs text-slate-600 mt-1">{e.rules}</p>}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {plan.logistics && (
              <div>
                <h4 className="font-black text-slate-700 text-sm uppercase tracking-wider mb-3 flex items-center gap-2"><Package size={16} className="text-yellow-600" /> Logistics</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {Object.entries(plan.logistics).map(([key, val]: [string, any]) => (
                    <div key={key} className="p-3 bg-slate-50 rounded-xl">
                      <p className="text-xs font-black text-slate-600 uppercase tracking-wider mb-1">{key}</p>
                      <p className="text-sm text-slate-700">{val}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {plan.announcements?.length > 0 && (
              <div className="p-4 bg-emerald-50 rounded-2xl border border-emerald-100">
                <h4 className="font-black text-emerald-700 text-sm uppercase tracking-wider mb-3 flex items-center gap-2"><Megaphone size={14} /> Announcements</h4>
                {plan.announcements.map((a: string, i: number) => <p key={i} className="text-sm text-emerald-800 mb-1">📢 {a}</p>)}
              </div>
            )}
          </div>

          <div className="px-6 pb-6 flex gap-3 flex-wrap">
            <button onClick={handleWhatsApp} className="flex items-center gap-2 px-4 py-2.5 bg-emerald-600 text-white rounded-xl text-sm font-bold hover:bg-emerald-700 transition-colors">
              <Share2 size={16} /> Share on WhatsApp
            </button>
            <button onClick={() => window.print()} className="flex items-center gap-2 px-4 py-2.5 bg-slate-100 text-slate-600 rounded-xl text-sm font-bold hover:bg-slate-200 transition-colors">
              🖨️ Print
            </button>
            <button onClick={() => setPlan(null)} className="flex items-center gap-2 px-4 py-2.5 bg-slate-100 text-slate-600 rounded-xl text-sm font-bold hover:bg-slate-200 transition-colors">
              <RotateCcw size={16} /> New Plan
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default SportsDayPlanner;
